#############################################################################
# Makefile for building: LLVMBuilderGUI.app/Contents/MacOS/LLVMBuilderGUI
# Generated by qmake (3.1) (Qt 6.9.0)
# Project:  LLVMBuilderGUI.pro
# Template: app
# Command: /opt/Qt/6.9.0/macos/bin/qmake -o Makefile LLVMBuilderGUI.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.4.sdk -mmacosx-version-min=12 -Wall -Wextra $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -O2 -std=gnu++1z $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.4.sdk -mmacosx-version-min=12 -Wall -Wextra $(DEFINES)
INCPATH       = -I. -I/opt/Qt/6.9.0/macos/lib/QtWidgets.framework/Headers -I/opt/Qt/6.9.0/macos/lib/QtGui.framework/Headers -I/opt/Qt/6.9.0/macos/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.4.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.4.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.4.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.4.sdk/System/Library/Frameworks/AGL.framework/Headers -I/opt/Qt/6.9.0/macos/mkspecs/macx-clang -F/opt/Qt/6.9.0/macos/lib
QMAKE         = /opt/Qt/6.9.0/macos/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /opt/Qt/6.9.0/macos/bin/qmake -install qinstall
QINSTALL_PROGRAM = /opt/Qt/6.9.0/macos/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = LLVMBuilderGUI1.0.0
DISTDIR = /Users/andrewsmith/Desktop/llvm/REPO2/llmtools/.tmp/LLVMBuilderGUI1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -stdlib=libc++ -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.4.sdk -mmacosx-version-min=12 -Wl,-rpath,@executable_path/../Frameworks -Wl,-rpath,/opt/Qt/6.9.0/macos/lib
LIBS          = $(SUBLIBS) -F/opt/Qt/6.9.0/macos/lib -framework QtWidgets -framework QtGui -framework AppKit -framework ImageIO -framework Metal -framework QtCore -framework IOKit -framework DiskArbitration -framework UniformTypeIdentifiers -framework AGL -framework OpenGL   
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		builderconfiguration.cpp \
		commandgenerator.cpp \
		buildexecutor.cpp \
		configurationdialog.cpp \
		fielddefaultsmanager.cpp moc_mainwindow.cpp \
		moc_buildexecutor.cpp \
		moc_configurationdialog.cpp
OBJECTS       = main.o \
		mainwindow.o \
		builderconfiguration.o \
		commandgenerator.o \
		buildexecutor.o \
		configurationdialog.o \
		fielddefaultsmanager.o \
		moc_mainwindow.o \
		moc_buildexecutor.o \
		moc_configurationdialog.o
DIST          = /opt/Qt/6.9.0/macos/mkspecs/features/spec_pre.prf \
		/opt/Qt/6.9.0/macos/mkspecs/features/device_config.prf \
		/opt/Qt/6.9.0/macos/mkspecs/common/unix.conf \
		/opt/Qt/6.9.0/macos/mkspecs/common/mac.conf \
		/opt/Qt/6.9.0/macos/mkspecs/common/macx.conf \
		/opt/Qt/6.9.0/macos/mkspecs/common/sanitize.conf \
		/opt/Qt/6.9.0/macos/mkspecs/common/gcc-base.conf \
		/opt/Qt/6.9.0/macos/mkspecs/common/gcc-base-mac.conf \
		/opt/Qt/6.9.0/macos/mkspecs/common/clang.conf \
		/opt/Qt/6.9.0/macos/mkspecs/common/clang-mac.conf \
		/opt/Qt/6.9.0/macos/mkspecs/qconfig.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_ext_freetype.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_ext_libjpeg.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_ext_libpng.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_core.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_core_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_dbus.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_designer.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_designer_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_example_icons_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_examples_asset_downloader_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_fb_support_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_freetype_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_gui.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_harfbuzz_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_help.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_help_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_jpeg_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_labsanimation.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_labsanimation_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_labsplatform.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_labsplatform_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_labssettings.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_labssettings_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_labssharedimage.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_linguist.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_network.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_network_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_opengl.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_openglwidgets.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_png_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_qdoccatch_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_qdoccatchconversions_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_qdoccatchgenerators_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_qml.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmlassetdownloader.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmlassetdownloader_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmlcompiler.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmlcore.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmlcore_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmldom_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmlformat_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmlintegration.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmlintegration_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmlls_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmlmeta.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmlmeta_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmlmodels.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmlnetwork.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmlnetwork_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmltoolingsettings_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quick.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2basic.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2basic_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2fluentwinui3styleimpl.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2fluentwinui3styleimpl_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2fusion.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2fusion_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2imagine.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2imagine_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2iosstyleimpl.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2iosstyleimpl_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2macosstyleimpl.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2macosstyleimpl_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2material.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2material_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2universal.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2universal_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickdialogs2.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickeffects.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickeffects_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quicklayouts.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickvectorimage.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickvectorimage_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickvectorimagegenerator_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_sql.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_svg.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_svgwidgets.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_testinternals_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_testlib.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_tools_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_uiplugin.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_uitools.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_widgets.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_xml.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_plugin_qdarwinbluetoothpermission.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_plugin_qdarwincalendarpermission.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_plugin_qdarwincamerapermission.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_plugin_qdarwincontactspermission.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_plugin_qdarwinlocationpermission.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_plugin_qdarwinmicrophonepermission.pri \
		/opt/Qt/6.9.0/macos/mkspecs/features/qt_functions.prf \
		/opt/Qt/6.9.0/macos/mkspecs/features/qt_config.prf \
		/opt/Qt/6.9.0/macos/mkspecs/macx-clang/qmake.conf \
		/opt/Qt/6.9.0/macos/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/opt/Qt/6.9.0/macos/mkspecs/features/exclusive_builds.prf \
		/opt/Qt/6.9.0/macos/mkspecs/features/mac/sdk.prf \
		/opt/Qt/6.9.0/macos/mkspecs/features/toolchain.prf \
		/opt/Qt/6.9.0/macos/mkspecs/features/mac/toolchain.prf \
		/opt/Qt/6.9.0/macos/mkspecs/features/default_pre.prf \
		/opt/Qt/6.9.0/macos/mkspecs/features/mac/default_pre.prf \
		/opt/Qt/6.9.0/macos/mkspecs/features/resolve_config.prf \
		/opt/Qt/6.9.0/macos/mkspecs/features/default_post.prf \
		/opt/Qt/6.9.0/macos/mkspecs/features/mac/default_post.prf \
		/opt/Qt/6.9.0/macos/mkspecs/features/mac/objective_c.prf \
		/opt/Qt/6.9.0/macos/mkspecs/features/mac/mac.prf \
		/opt/Qt/6.9.0/macos/mkspecs/features/warn_on.prf \
		/opt/Qt/6.9.0/macos/mkspecs/features/permissions.prf \
		/opt/Qt/6.9.0/macos/mkspecs/features/qt.prf \
		/opt/Qt/6.9.0/macos/mkspecs/features/resources_functions.prf \
		/opt/Qt/6.9.0/macos/mkspecs/features/resources.prf \
		/opt/Qt/6.9.0/macos/mkspecs/features/moc.prf \
		/opt/Qt/6.9.0/macos/mkspecs/features/unix/opengl.prf \
		/opt/Qt/6.9.0/macos/mkspecs/features/uic.prf \
		/opt/Qt/6.9.0/macos/mkspecs/features/unix/thread.prf \
		/opt/Qt/6.9.0/macos/mkspecs/features/qmake_use.prf \
		/opt/Qt/6.9.0/macos/mkspecs/features/file_copies.prf \
		/opt/Qt/6.9.0/macos/mkspecs/features/mac/rez.prf \
		/opt/Qt/6.9.0/macos/mkspecs/features/mac/asset_catalogs.prf \
		/opt/Qt/6.9.0/macos/mkspecs/features/testcase_targets.prf \
		/opt/Qt/6.9.0/macos/mkspecs/features/exceptions.prf \
		/opt/Qt/6.9.0/macos/mkspecs/features/yacc.prf \
		/opt/Qt/6.9.0/macos/mkspecs/features/lex.prf \
		LLVMBuilderGUI.pro mainwindow.h \
		builderconfiguration.h \
		commandgenerator.h \
		buildexecutor.h \
		configurationdialog.h \
		fielddefaultsmanager.h main.cpp \
		mainwindow.cpp \
		builderconfiguration.cpp \
		commandgenerator.cpp \
		buildexecutor.cpp \
		configurationdialog.cpp \
		fielddefaultsmanager.cpp
QMAKE_TARGET  = LLVMBuilderGUI
DESTDIR       = 
TARGET        = LLVMBuilderGUI.app/Contents/MacOS/LLVMBuilderGUI

####### Custom Variables
EXPORT_QMAKE_MAC_SDK = macosx
EXPORT_QMAKE_MAC_SDK_VERSION = 15.4
EXPORT_QMAKE_XCODE_DEVELOPER_PATH = /Applications/Xcode.app/Contents/Developer
EXPORT__QMAKE_STASH_ = /Users/andrewsmith/Desktop/llvm/REPO2/llmtools/.qmake.stash
EXPORT_VALID_ARCHS = x86_64 arm64
EXPORT_DEFAULT_ARCHS = arm64
EXPORT_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(if $(ARCHS), $(ARCHS), $(if $(EXPORT_DEFAULT_ARCHS), $(EXPORT_DEFAULT_ARCHS), $(EXPORT_VALID_ARCHS))))
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ARCHS), $(EXPORT_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))
EXPORT__PRO_FILE_ = /Users/andrewsmith/Desktop/llvm/REPO2/llmtools/LLVMBuilderGUI.pro


include /opt/Qt/6.9.0/macos/mkspecs/features/mac/sdk.mk
first: all
####### Build rules

LLVMBuilderGUI.app/Contents/MacOS/LLVMBuilderGUI: ui_mainwindow.h ui_configurationdialog.h $(OBJECTS)  
	@test -d LLVMBuilderGUI.app/Contents/MacOS/ || mkdir -p LLVMBuilderGUI.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET)  $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: LLVMBuilderGUI.pro /opt/Qt/6.9.0/macos/mkspecs/macx-clang/qmake.conf /opt/Qt/6.9.0/macos/mkspecs/features/spec_pre.prf \
		/opt/Qt/6.9.0/macos/mkspecs/features/device_config.prf \
		/opt/Qt/6.9.0/macos/mkspecs/common/unix.conf \
		/opt/Qt/6.9.0/macos/mkspecs/common/mac.conf \
		/opt/Qt/6.9.0/macos/mkspecs/common/macx.conf \
		/opt/Qt/6.9.0/macos/mkspecs/common/sanitize.conf \
		/opt/Qt/6.9.0/macos/mkspecs/common/gcc-base.conf \
		/opt/Qt/6.9.0/macos/mkspecs/common/gcc-base-mac.conf \
		/opt/Qt/6.9.0/macos/mkspecs/common/clang.conf \
		/opt/Qt/6.9.0/macos/mkspecs/common/clang-mac.conf \
		/opt/Qt/6.9.0/macos/mkspecs/qconfig.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_ext_freetype.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_ext_libjpeg.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_ext_libpng.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_core.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_core_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_dbus.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_designer.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_designer_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_example_icons_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_examples_asset_downloader_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_fb_support_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_freetype_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_gui.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_harfbuzz_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_help.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_help_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_jpeg_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_labsanimation.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_labsanimation_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_labsplatform.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_labsplatform_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_labssettings.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_labssettings_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_labssharedimage.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_linguist.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_network.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_network_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_opengl.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_openglwidgets.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_png_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_qdoccatch_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_qdoccatchconversions_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_qdoccatchgenerators_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_qml.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmlassetdownloader.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmlassetdownloader_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmlcompiler.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmlcore.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmlcore_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmldom_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmlformat_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmlintegration.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmlintegration_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmlls_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmlmeta.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmlmeta_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmlmodels.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmlnetwork.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmlnetwork_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmltoolingsettings_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quick.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2basic.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2basic_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2fluentwinui3styleimpl.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2fluentwinui3styleimpl_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2fusion.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2fusion_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2imagine.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2imagine_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2iosstyleimpl.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2iosstyleimpl_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2macosstyleimpl.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2macosstyleimpl_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2material.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2material_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2universal.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2universal_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickdialogs2.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickeffects.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickeffects_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quicklayouts.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickvectorimage.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickvectorimage_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickvectorimagegenerator_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_sql.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_svg.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_svgwidgets.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_testinternals_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_testlib.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_tools_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_uiplugin.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_uitools.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_widgets.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_xml.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_plugin_qdarwinbluetoothpermission.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_plugin_qdarwincalendarpermission.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_plugin_qdarwincamerapermission.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_plugin_qdarwincontactspermission.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_plugin_qdarwinlocationpermission.pri \
		/opt/Qt/6.9.0/macos/mkspecs/modules/qt_plugin_qdarwinmicrophonepermission.pri \
		/opt/Qt/6.9.0/macos/mkspecs/features/qt_functions.prf \
		/opt/Qt/6.9.0/macos/mkspecs/features/qt_config.prf \
		/opt/Qt/6.9.0/macos/mkspecs/macx-clang/qmake.conf \
		/opt/Qt/6.9.0/macos/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/opt/Qt/6.9.0/macos/mkspecs/features/exclusive_builds.prf \
		/opt/Qt/6.9.0/macos/mkspecs/features/mac/sdk.prf \
		/opt/Qt/6.9.0/macos/mkspecs/features/toolchain.prf \
		/opt/Qt/6.9.0/macos/mkspecs/features/mac/toolchain.prf \
		/opt/Qt/6.9.0/macos/mkspecs/features/default_pre.prf \
		/opt/Qt/6.9.0/macos/mkspecs/features/mac/default_pre.prf \
		/opt/Qt/6.9.0/macos/mkspecs/features/resolve_config.prf \
		/opt/Qt/6.9.0/macos/mkspecs/features/default_post.prf \
		/opt/Qt/6.9.0/macos/mkspecs/features/mac/default_post.prf \
		/opt/Qt/6.9.0/macos/mkspecs/features/mac/objective_c.prf \
		/opt/Qt/6.9.0/macos/mkspecs/features/mac/mac.prf \
		/opt/Qt/6.9.0/macos/mkspecs/features/warn_on.prf \
		/opt/Qt/6.9.0/macos/mkspecs/features/permissions.prf \
		/opt/Qt/6.9.0/macos/mkspecs/features/qt.prf \
		/opt/Qt/6.9.0/macos/mkspecs/features/resources_functions.prf \
		/opt/Qt/6.9.0/macos/mkspecs/features/resources.prf \
		/opt/Qt/6.9.0/macos/mkspecs/features/moc.prf \
		/opt/Qt/6.9.0/macos/mkspecs/features/unix/opengl.prf \
		/opt/Qt/6.9.0/macos/mkspecs/features/uic.prf \
		/opt/Qt/6.9.0/macos/mkspecs/features/unix/thread.prf \
		/opt/Qt/6.9.0/macos/mkspecs/features/qmake_use.prf \
		/opt/Qt/6.9.0/macos/mkspecs/features/file_copies.prf \
		/opt/Qt/6.9.0/macos/mkspecs/features/mac/rez.prf \
		/opt/Qt/6.9.0/macos/mkspecs/features/mac/asset_catalogs.prf \
		/opt/Qt/6.9.0/macos/mkspecs/features/testcase_targets.prf \
		/opt/Qt/6.9.0/macos/mkspecs/features/exceptions.prf \
		/opt/Qt/6.9.0/macos/mkspecs/features/yacc.prf \
		/opt/Qt/6.9.0/macos/mkspecs/features/lex.prf \
		LLVMBuilderGUI.pro \
		/opt/Qt/6.9.0/macos/lib/QtWidgets.framework/Resources/QtWidgets.prl \
		/opt/Qt/6.9.0/macos/lib/QtGui.framework/Resources/QtGui.prl \
		/opt/Qt/6.9.0/macos/lib/QtCore.framework/Resources/QtCore.prl
	$(QMAKE) -o Makefile LLVMBuilderGUI.pro
/opt/Qt/6.9.0/macos/mkspecs/features/spec_pre.prf:
/opt/Qt/6.9.0/macos/mkspecs/features/device_config.prf:
/opt/Qt/6.9.0/macos/mkspecs/common/unix.conf:
/opt/Qt/6.9.0/macos/mkspecs/common/mac.conf:
/opt/Qt/6.9.0/macos/mkspecs/common/macx.conf:
/opt/Qt/6.9.0/macos/mkspecs/common/sanitize.conf:
/opt/Qt/6.9.0/macos/mkspecs/common/gcc-base.conf:
/opt/Qt/6.9.0/macos/mkspecs/common/gcc-base-mac.conf:
/opt/Qt/6.9.0/macos/mkspecs/common/clang.conf:
/opt/Qt/6.9.0/macos/mkspecs/common/clang-mac.conf:
/opt/Qt/6.9.0/macos/mkspecs/qconfig.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_ext_freetype.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_ext_libjpeg.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_ext_libpng.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_concurrent.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_concurrent_private.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_core.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_core_private.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_dbus.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_dbus_private.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_designer.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_designer_private.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_designercomponents_private.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_example_icons_private.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_examples_asset_downloader_private.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_fb_support_private.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_freetype_private.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_gui.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_gui_private.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_harfbuzz_private.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_help.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_help_private.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_jpeg_private.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_labsanimation.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_labsanimation_private.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_labsfolderlistmodel.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_labsplatform.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_labsplatform_private.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_labsqmlmodels.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_labsqmlmodels_private.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_labssettings.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_labssettings_private.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_labssharedimage.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_labssharedimage_private.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_labswavefrontmesh.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_linguist.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_network.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_network_private.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_opengl.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_opengl_private.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_openglwidgets.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_openglwidgets_private.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_png_private.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_printsupport.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_printsupport_private.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_qdoccatch_private.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_qdoccatchconversions_private.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_qdoccatchgenerators_private.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_qml.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_qml_private.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmlassetdownloader.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmlassetdownloader_private.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmlcompiler.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmlcompiler_private.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmlcore.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmlcore_private.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmldebug_private.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmldom_private.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmlformat_private.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmlintegration.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmlintegration_private.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmllocalstorage.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmllocalstorage_private.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmlls_private.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmlmeta.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmlmeta_private.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmlmodels.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmlmodels_private.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmlnetwork.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmlnetwork_private.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmltest.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmltest_private.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmltoolingsettings_private.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmlxmllistmodel.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quick.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quick_private.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2basic.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2basic_private.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl_private.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2fluentwinui3styleimpl.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2fluentwinui3styleimpl_private.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2fusion.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2fusion_private.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl_private.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2imagine.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2imagine_private.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl_private.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2impl.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2iosstyleimpl.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2iosstyleimpl_private.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2macosstyleimpl.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2macosstyleimpl_private.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2material.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2material_private.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl_private.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2universal.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2universal_private.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl_private.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickdialogs2.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickdialogs2_private.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickdialogs2utils.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickeffects.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickeffects_private.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quicklayouts.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quicklayouts_private.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickparticles_private.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickshapes_private.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quicktemplates2.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickvectorimage.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickvectorimage_private.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickvectorimagegenerator_private.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickwidgets.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_sql.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_sql_private.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_svg.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_svg_private.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_svgwidgets.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_svgwidgets_private.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_testinternals_private.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_testlib.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_testlib_private.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_tools_private.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_uiplugin.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_uitools.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_uitools_private.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_widgets.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_widgets_private.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_xml.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_lib_xml_private.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_plugin_qdarwinbluetoothpermission.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_plugin_qdarwincalendarpermission.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_plugin_qdarwincamerapermission.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_plugin_qdarwincontactspermission.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_plugin_qdarwinlocationpermission.pri:
/opt/Qt/6.9.0/macos/mkspecs/modules/qt_plugin_qdarwinmicrophonepermission.pri:
/opt/Qt/6.9.0/macos/mkspecs/features/qt_functions.prf:
/opt/Qt/6.9.0/macos/mkspecs/features/qt_config.prf:
/opt/Qt/6.9.0/macos/mkspecs/macx-clang/qmake.conf:
/opt/Qt/6.9.0/macos/mkspecs/features/spec_post.prf:
.qmake.stash:
/opt/Qt/6.9.0/macos/mkspecs/features/exclusive_builds.prf:
/opt/Qt/6.9.0/macos/mkspecs/features/mac/sdk.prf:
/opt/Qt/6.9.0/macos/mkspecs/features/toolchain.prf:
/opt/Qt/6.9.0/macos/mkspecs/features/mac/toolchain.prf:
/opt/Qt/6.9.0/macos/mkspecs/features/default_pre.prf:
/opt/Qt/6.9.0/macos/mkspecs/features/mac/default_pre.prf:
/opt/Qt/6.9.0/macos/mkspecs/features/resolve_config.prf:
/opt/Qt/6.9.0/macos/mkspecs/features/default_post.prf:
/opt/Qt/6.9.0/macos/mkspecs/features/mac/default_post.prf:
/opt/Qt/6.9.0/macos/mkspecs/features/mac/objective_c.prf:
/opt/Qt/6.9.0/macos/mkspecs/features/mac/mac.prf:
/opt/Qt/6.9.0/macos/mkspecs/features/warn_on.prf:
/opt/Qt/6.9.0/macos/mkspecs/features/permissions.prf:
/opt/Qt/6.9.0/macos/mkspecs/features/qt.prf:
/opt/Qt/6.9.0/macos/mkspecs/features/resources_functions.prf:
/opt/Qt/6.9.0/macos/mkspecs/features/resources.prf:
/opt/Qt/6.9.0/macos/mkspecs/features/moc.prf:
/opt/Qt/6.9.0/macos/mkspecs/features/unix/opengl.prf:
/opt/Qt/6.9.0/macos/mkspecs/features/uic.prf:
/opt/Qt/6.9.0/macos/mkspecs/features/unix/thread.prf:
/opt/Qt/6.9.0/macos/mkspecs/features/qmake_use.prf:
/opt/Qt/6.9.0/macos/mkspecs/features/file_copies.prf:
/opt/Qt/6.9.0/macos/mkspecs/features/mac/rez.prf:
/opt/Qt/6.9.0/macos/mkspecs/features/mac/asset_catalogs.prf:
/opt/Qt/6.9.0/macos/mkspecs/features/testcase_targets.prf:
/opt/Qt/6.9.0/macos/mkspecs/features/exceptions.prf:
/opt/Qt/6.9.0/macos/mkspecs/features/yacc.prf:
/opt/Qt/6.9.0/macos/mkspecs/features/lex.prf:
LLVMBuilderGUI.pro:
/opt/Qt/6.9.0/macos/lib/QtWidgets.framework/Resources/QtWidgets.prl:
/opt/Qt/6.9.0/macos/lib/QtGui.framework/Resources/QtGui.prl:
/opt/Qt/6.9.0/macos/lib/QtCore.framework/Resources/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile LLVMBuilderGUI.pro

qmake_all: FORCE

LLVMBuilderGUI.app/Contents/PkgInfo: 
	@test -d LLVMBuilderGUI.app/Contents || mkdir -p LLVMBuilderGUI.app/Contents
	@$(DEL_FILE) LLVMBuilderGUI.app/Contents/PkgInfo
	@echo "APPL????" > LLVMBuilderGUI.app/Contents/PkgInfo
LLVMBuilderGUI.app/Contents/Info.plist: 
	@test -d LLVMBuilderGUI.app/Contents || mkdir -p LLVMBuilderGUI.app/Contents
	@$(DEL_FILE) LLVMBuilderGUI.app/Contents/Info.plist
	@plutil -convert xml1 -o - /opt/Qt/6.9.0/macos/mkspecs/macx-clang/Info.plist.app | sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,\$${QMAKE_SHORT_VERSION},1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,\$${QMAKE_FULL_VERSION},1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" -e "s,@BUNDLEIDENTIFIER@,com.andrewjosephsmith.AJLib.LibScrambleArray.LLVMBuilderGUI,g" -e "s,\$${PRODUCT_BUNDLE_IDENTIFIER},com.andrewjosephsmith.AJLib.LibScrambleArray.LLVMBuilderGUI,g" -e "s,\$${MACOSX_DEPLOYMENT_TARGET},12,g" -e "s,\$${IPHONEOS_DEPLOYMENT_TARGET},,g" -e "s,\$${TVOS_DEPLOYMENT_TARGET},,g" -e "s,\$${WATCHOS_DEPLOYMENT_TARGET},,g" -e "s,\$${IOS_LAUNCH_SCREEN},LaunchScreen,g" -e "s,@ICON@,,g" -e "s,\$${ASSETCATALOG_COMPILER_APPICON_NAME},,g" -e "s,@EXECUTABLE@,LLVMBuilderGUI,g" -e "s,@LIBRARY@,LLVMBuilderGUI,g" -e "s,\$${EXECUTABLE_NAME},LLVMBuilderGUI,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" >LLVMBuilderGUI.app/Contents/Info.plist

all: Makefile \
		LLVMBuilderGUI.app/Contents/PkgInfo \
		LLVMBuilderGUI.app/Contents/Info.plist LLVMBuilderGUI.app/Contents/MacOS/LLVMBuilderGUI

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.h builderconfiguration.h commandgenerator.h buildexecutor.h configurationdialog.h fielddefaultsmanager.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp mainwindow.cpp builderconfiguration.cpp commandgenerator.cpp buildexecutor.cpp configurationdialog.cpp fielddefaultsmanager.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.ui configurationdialog.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r LLVMBuilderGUI.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

xcodeproj:
	@$(QMAKE) -spec macx-xcode "$(EXPORT__PRO_FILE_)"

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_mainwindow.cpp moc_buildexecutor.cpp moc_configurationdialog.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_buildexecutor.cpp moc_configurationdialog.cpp
moc_mainwindow.cpp: mainwindow.h \
		/opt/Qt/6.9.0/macos/lib/QtWidgets.framework/Headers/QMainWindow \
		/opt/Qt/6.9.0/macos/lib/QtWidgets.framework/Headers/qmainwindow.h \
		/opt/Qt/6.9.0/macos/lib/QtCore.framework/Headers/QMap \
		/opt/Qt/6.9.0/macos/lib/QtCore.framework/Headers/qmap.h \
		/opt/Qt/6.9.0/macos/lib/QtCore.framework/Headers/QString \
		/opt/Qt/6.9.0/macos/lib/QtCore.framework/Headers/qstring.h \
		/opt/Qt/6.9.0/macos/lib/QtWidgets.framework/Headers/QLineEdit \
		/opt/Qt/6.9.0/macos/lib/QtWidgets.framework/Headers/qlineedit.h \
		/opt/Qt/6.9.0/macos/lib/QtWidgets.framework/Headers/QPushButton \
		/opt/Qt/6.9.0/macos/lib/QtWidgets.framework/Headers/qpushbutton.h \
		/opt/Qt/6.9.0/macos/libexec/moc
	/opt/Qt/6.9.0/macos/libexec/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -D__cplusplus=201402L -D__APPLE_CC__=6000 -D__clang__ -D__clang_major__=17 -D__clang_minor__=0 -D__clang_patchlevel__=0 -D__GNUC__=4 -D__GNUC_MINOR__=2 -D__GNUC_PATCHLEVEL__=1 -I/opt/Qt/6.9.0/macos/mkspecs/macx-clang -I/Users/andrewsmith/Desktop/llvm/REPO2/llmtools -I/opt/Qt/6.9.0/macos/lib/QtWidgets.framework/Headers -I/opt/Qt/6.9.0/macos/lib/QtGui.framework/Headers -I/opt/Qt/6.9.0/macos/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.4.sdk/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/17/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.4.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/opt/Qt/6.9.0/macos/lib mainwindow.h -o moc_mainwindow.cpp

moc_buildexecutor.cpp: buildexecutor.h \
		/opt/Qt/6.9.0/macos/lib/QtCore.framework/Headers/QObject \
		/opt/Qt/6.9.0/macos/lib/QtCore.framework/Headers/qobject.h \
		/opt/Qt/6.9.0/macos/lib/QtCore.framework/Headers/QProcess \
		/opt/Qt/6.9.0/macos/lib/QtCore.framework/Headers/qprocess.h \
		/opt/Qt/6.9.0/macos/lib/QtCore.framework/Headers/QString \
		/opt/Qt/6.9.0/macos/lib/QtCore.framework/Headers/qstring.h \
		/opt/Qt/6.9.0/macos/lib/QtCore.framework/Headers/QTemporaryFile \
		/opt/Qt/6.9.0/macos/lib/QtCore.framework/Headers/qtemporaryfile.h \
		/opt/Qt/6.9.0/macos/libexec/moc
	/opt/Qt/6.9.0/macos/libexec/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -D__cplusplus=201402L -D__APPLE_CC__=6000 -D__clang__ -D__clang_major__=17 -D__clang_minor__=0 -D__clang_patchlevel__=0 -D__GNUC__=4 -D__GNUC_MINOR__=2 -D__GNUC_PATCHLEVEL__=1 -I/opt/Qt/6.9.0/macos/mkspecs/macx-clang -I/Users/andrewsmith/Desktop/llvm/REPO2/llmtools -I/opt/Qt/6.9.0/macos/lib/QtWidgets.framework/Headers -I/opt/Qt/6.9.0/macos/lib/QtGui.framework/Headers -I/opt/Qt/6.9.0/macos/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.4.sdk/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/17/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.4.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/opt/Qt/6.9.0/macos/lib buildexecutor.h -o moc_buildexecutor.cpp

moc_configurationdialog.cpp: configurationdialog.h \
		/opt/Qt/6.9.0/macos/lib/QtWidgets.framework/Headers/QDialog \
		/opt/Qt/6.9.0/macos/lib/QtWidgets.framework/Headers/qdialog.h \
		/opt/Qt/6.9.0/macos/lib/QtCore.framework/Headers/QMap \
		/opt/Qt/6.9.0/macos/lib/QtCore.framework/Headers/qmap.h \
		/opt/Qt/6.9.0/macos/lib/QtCore.framework/Headers/QString \
		/opt/Qt/6.9.0/macos/lib/QtCore.framework/Headers/qstring.h \
		/opt/Qt/6.9.0/macos/libexec/moc
	/opt/Qt/6.9.0/macos/libexec/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -D__cplusplus=201402L -D__APPLE_CC__=6000 -D__clang__ -D__clang_major__=17 -D__clang_minor__=0 -D__clang_patchlevel__=0 -D__GNUC__=4 -D__GNUC_MINOR__=2 -D__GNUC_PATCHLEVEL__=1 -I/opt/Qt/6.9.0/macos/mkspecs/macx-clang -I/Users/andrewsmith/Desktop/llvm/REPO2/llmtools -I/opt/Qt/6.9.0/macos/lib/QtWidgets.framework/Headers -I/opt/Qt/6.9.0/macos/lib/QtGui.framework/Headers -I/opt/Qt/6.9.0/macos/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.4.sdk/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/17/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.4.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/opt/Qt/6.9.0/macos/lib configurationdialog.h -o moc_configurationdialog.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_configurationdialog.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_configurationdialog.h
ui_mainwindow.h: mainwindow.ui \
		/opt/Qt/6.9.0/macos/libexec/uic
	/opt/Qt/6.9.0/macos/libexec/uic mainwindow.ui -o ui_mainwindow.h

ui_configurationdialog.h: configurationdialog.ui \
		/opt/Qt/6.9.0/macos/libexec/uic
	/opt/Qt/6.9.0/macos/libexec/uic configurationdialog.ui -o ui_configurationdialog.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		/opt/Qt/6.9.0/macos/lib/QtWidgets.framework/Headers/QMainWindow \
		/opt/Qt/6.9.0/macos/lib/QtWidgets.framework/Headers/qmainwindow.h \
		/opt/Qt/6.9.0/macos/lib/QtCore.framework/Headers/QMap \
		/opt/Qt/6.9.0/macos/lib/QtCore.framework/Headers/qmap.h \
		/opt/Qt/6.9.0/macos/lib/QtCore.framework/Headers/QString \
		/opt/Qt/6.9.0/macos/lib/QtCore.framework/Headers/qstring.h \
		/opt/Qt/6.9.0/macos/lib/QtWidgets.framework/Headers/QLineEdit \
		/opt/Qt/6.9.0/macos/lib/QtWidgets.framework/Headers/qlineedit.h \
		/opt/Qt/6.9.0/macos/lib/QtWidgets.framework/Headers/QPushButton \
		/opt/Qt/6.9.0/macos/lib/QtWidgets.framework/Headers/qpushbutton.h \
		/opt/Qt/6.9.0/macos/lib/QtWidgets.framework/Headers/QApplication \
		/opt/Qt/6.9.0/macos/lib/QtWidgets.framework/Headers/qapplication.h \
		/opt/Qt/6.9.0/macos/lib/QtCore.framework/Headers/QLocale \
		/opt/Qt/6.9.0/macos/lib/QtCore.framework/Headers/qlocale.h \
		/opt/Qt/6.9.0/macos/lib/QtCore.framework/Headers/QTranslator \
		/opt/Qt/6.9.0/macos/lib/QtCore.framework/Headers/qtranslator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		/opt/Qt/6.9.0/macos/lib/QtWidgets.framework/Headers/QMainWindow \
		/opt/Qt/6.9.0/macos/lib/QtWidgets.framework/Headers/qmainwindow.h \
		/opt/Qt/6.9.0/macos/lib/QtCore.framework/Headers/QMap \
		/opt/Qt/6.9.0/macos/lib/QtCore.framework/Headers/qmap.h \
		/opt/Qt/6.9.0/macos/lib/QtCore.framework/Headers/QString \
		/opt/Qt/6.9.0/macos/lib/QtCore.framework/Headers/qstring.h \
		/opt/Qt/6.9.0/macos/lib/QtWidgets.framework/Headers/QLineEdit \
		/opt/Qt/6.9.0/macos/lib/QtWidgets.framework/Headers/qlineedit.h \
		/opt/Qt/6.9.0/macos/lib/QtWidgets.framework/Headers/QPushButton \
		/opt/Qt/6.9.0/macos/lib/QtWidgets.framework/Headers/qpushbutton.h \
		ui_mainwindow.h \
		builderconfiguration.h \
		/opt/Qt/6.9.0/macos/lib/QtCore.framework/Headers/QVariant \
		/opt/Qt/6.9.0/macos/lib/QtCore.framework/Headers/qvariant.h \
		/opt/Qt/6.9.0/macos/lib/QtCore.framework/Headers/QJsonObject \
		/opt/Qt/6.9.0/macos/lib/QtCore.framework/Headers/qjsonobject.h \
		commandgenerator.h \
		buildexecutor.h \
		/opt/Qt/6.9.0/macos/lib/QtCore.framework/Headers/QObject \
		/opt/Qt/6.9.0/macos/lib/QtCore.framework/Headers/qobject.h \
		/opt/Qt/6.9.0/macos/lib/QtCore.framework/Headers/QProcess \
		/opt/Qt/6.9.0/macos/lib/QtCore.framework/Headers/qprocess.h \
		/opt/Qt/6.9.0/macos/lib/QtCore.framework/Headers/QTemporaryFile \
		/opt/Qt/6.9.0/macos/lib/QtCore.framework/Headers/qtemporaryfile.h \
		configurationdialog.h \
		/opt/Qt/6.9.0/macos/lib/QtWidgets.framework/Headers/QDialog \
		/opt/Qt/6.9.0/macos/lib/QtWidgets.framework/Headers/qdialog.h \
		fielddefaultsmanager.h \
		/opt/Qt/6.9.0/macos/lib/QtWidgets.framework/Headers/QToolBar \
		/opt/Qt/6.9.0/macos/lib/QtWidgets.framework/Headers/qtoolbar.h \
		/opt/Qt/6.9.0/macos/lib/QtWidgets.framework/Headers/QLabel \
		/opt/Qt/6.9.0/macos/lib/QtWidgets.framework/Headers/qlabel.h \
		/opt/Qt/6.9.0/macos/lib/QtWidgets.framework/Headers/QFileDialog \
		/opt/Qt/6.9.0/macos/lib/QtWidgets.framework/Headers/qfiledialog.h \
		/opt/Qt/6.9.0/macos/lib/QtWidgets.framework/Headers/QMessageBox \
		/opt/Qt/6.9.0/macos/lib/QtWidgets.framework/Headers/qmessagebox.h \
		/opt/Qt/6.9.0/macos/lib/QtGui.framework/Headers/QClipboard \
		/opt/Qt/6.9.0/macos/lib/QtGui.framework/Headers/qclipboard.h \
		/opt/Qt/6.9.0/macos/lib/QtWidgets.framework/Headers/QApplication \
		/opt/Qt/6.9.0/macos/lib/QtWidgets.framework/Headers/qapplication.h \
		/opt/Qt/6.9.0/macos/lib/QtCore.framework/Headers/QTextStream \
		/opt/Qt/6.9.0/macos/lib/QtCore.framework/Headers/qtextstream.h \
		/opt/Qt/6.9.0/macos/lib/QtCore.framework/Headers/QFile \
		/opt/Qt/6.9.0/macos/lib/QtCore.framework/Headers/qfile.h \
		/opt/Qt/6.9.0/macos/lib/QtCore.framework/Headers/QDateTime \
		/opt/Qt/6.9.0/macos/lib/QtCore.framework/Headers/qdatetime.h \
		/opt/Qt/6.9.0/macos/lib/QtCore.framework/Headers/QDir \
		/opt/Qt/6.9.0/macos/lib/QtCore.framework/Headers/qdir.h \
		/opt/Qt/6.9.0/macos/lib/QtWidgets.framework/Headers/QScrollBar \
		/opt/Qt/6.9.0/macos/lib/QtWidgets.framework/Headers/qscrollbar.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

builderconfiguration.o: builderconfiguration.cpp builderconfiguration.h \
		/opt/Qt/6.9.0/macos/lib/QtCore.framework/Headers/QString \
		/opt/Qt/6.9.0/macos/lib/QtCore.framework/Headers/qstring.h \
		/opt/Qt/6.9.0/macos/lib/QtCore.framework/Headers/QMap \
		/opt/Qt/6.9.0/macos/lib/QtCore.framework/Headers/qmap.h \
		/opt/Qt/6.9.0/macos/lib/QtCore.framework/Headers/QVariant \
		/opt/Qt/6.9.0/macos/lib/QtCore.framework/Headers/qvariant.h \
		/opt/Qt/6.9.0/macos/lib/QtCore.framework/Headers/QJsonObject \
		/opt/Qt/6.9.0/macos/lib/QtCore.framework/Headers/qjsonobject.h \
		/opt/Qt/6.9.0/macos/lib/QtCore.framework/Headers/QJsonDocument \
		/opt/Qt/6.9.0/macos/lib/QtCore.framework/Headers/qjsondocument.h \
		/opt/Qt/6.9.0/macos/lib/QtCore.framework/Headers/QFile \
		/opt/Qt/6.9.0/macos/lib/QtCore.framework/Headers/qfile.h \
		/opt/Qt/6.9.0/macos/lib/QtCore.framework/Headers/QDir \
		/opt/Qt/6.9.0/macos/lib/QtCore.framework/Headers/qdir.h \
		/opt/Qt/6.9.0/macos/lib/QtCore.framework/Headers/QStandardPaths \
		/opt/Qt/6.9.0/macos/lib/QtCore.framework/Headers/qstandardpaths.h \
		/opt/Qt/6.9.0/macos/lib/QtCore.framework/Headers/QTemporaryDir \
		/opt/Qt/6.9.0/macos/lib/QtCore.framework/Headers/qtemporarydir.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o builderconfiguration.o builderconfiguration.cpp

commandgenerator.o: commandgenerator.cpp commandgenerator.h \
		builderconfiguration.h \
		/opt/Qt/6.9.0/macos/lib/QtCore.framework/Headers/QString \
		/opt/Qt/6.9.0/macos/lib/QtCore.framework/Headers/qstring.h \
		/opt/Qt/6.9.0/macos/lib/QtCore.framework/Headers/QMap \
		/opt/Qt/6.9.0/macos/lib/QtCore.framework/Headers/qmap.h \
		/opt/Qt/6.9.0/macos/lib/QtCore.framework/Headers/QVariant \
		/opt/Qt/6.9.0/macos/lib/QtCore.framework/Headers/qvariant.h \
		/opt/Qt/6.9.0/macos/lib/QtCore.framework/Headers/QJsonObject \
		/opt/Qt/6.9.0/macos/lib/QtCore.framework/Headers/qjsonobject.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o commandgenerator.o commandgenerator.cpp

buildexecutor.o: buildexecutor.cpp buildexecutor.h \
		/opt/Qt/6.9.0/macos/lib/QtCore.framework/Headers/QObject \
		/opt/Qt/6.9.0/macos/lib/QtCore.framework/Headers/qobject.h \
		/opt/Qt/6.9.0/macos/lib/QtCore.framework/Headers/QProcess \
		/opt/Qt/6.9.0/macos/lib/QtCore.framework/Headers/qprocess.h \
		/opt/Qt/6.9.0/macos/lib/QtCore.framework/Headers/QString \
		/opt/Qt/6.9.0/macos/lib/QtCore.framework/Headers/qstring.h \
		/opt/Qt/6.9.0/macos/lib/QtCore.framework/Headers/QTemporaryFile \
		/opt/Qt/6.9.0/macos/lib/QtCore.framework/Headers/qtemporaryfile.h \
		builderconfiguration.h \
		/opt/Qt/6.9.0/macos/lib/QtCore.framework/Headers/QMap \
		/opt/Qt/6.9.0/macos/lib/QtCore.framework/Headers/qmap.h \
		/opt/Qt/6.9.0/macos/lib/QtCore.framework/Headers/QVariant \
		/opt/Qt/6.9.0/macos/lib/QtCore.framework/Headers/qvariant.h \
		/opt/Qt/6.9.0/macos/lib/QtCore.framework/Headers/QJsonObject \
		/opt/Qt/6.9.0/macos/lib/QtCore.framework/Headers/qjsonobject.h \
		commandgenerator.h \
		/opt/Qt/6.9.0/macos/lib/QtCore.framework/Headers/QDir \
		/opt/Qt/6.9.0/macos/lib/QtCore.framework/Headers/qdir.h \
		/opt/Qt/6.9.0/macos/lib/QtCore.framework/Headers/QFileInfo \
		/opt/Qt/6.9.0/macos/lib/QtCore.framework/Headers/qfileinfo.h \
		/opt/Qt/6.9.0/macos/lib/QtCore.framework/Headers/QTextStream \
		/opt/Qt/6.9.0/macos/lib/QtCore.framework/Headers/qtextstream.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o buildexecutor.o buildexecutor.cpp

configurationdialog.o: configurationdialog.cpp configurationdialog.h \
		/opt/Qt/6.9.0/macos/lib/QtWidgets.framework/Headers/QDialog \
		/opt/Qt/6.9.0/macos/lib/QtWidgets.framework/Headers/qdialog.h \
		/opt/Qt/6.9.0/macos/lib/QtCore.framework/Headers/QMap \
		/opt/Qt/6.9.0/macos/lib/QtCore.framework/Headers/qmap.h \
		/opt/Qt/6.9.0/macos/lib/QtCore.framework/Headers/QString \
		/opt/Qt/6.9.0/macos/lib/QtCore.framework/Headers/qstring.h \
		ui_configurationdialog.h \
		builderconfiguration.h \
		/opt/Qt/6.9.0/macos/lib/QtCore.framework/Headers/QVariant \
		/opt/Qt/6.9.0/macos/lib/QtCore.framework/Headers/qvariant.h \
		/opt/Qt/6.9.0/macos/lib/QtCore.framework/Headers/QJsonObject \
		/opt/Qt/6.9.0/macos/lib/QtCore.framework/Headers/qjsonobject.h \
		/opt/Qt/6.9.0/macos/lib/QtCore.framework/Headers/QDir \
		/opt/Qt/6.9.0/macos/lib/QtCore.framework/Headers/qdir.h \
		/opt/Qt/6.9.0/macos/lib/QtCore.framework/Headers/QStandardPaths \
		/opt/Qt/6.9.0/macos/lib/QtCore.framework/Headers/qstandardpaths.h \
		/opt/Qt/6.9.0/macos/lib/QtWidgets.framework/Headers/QMessageBox \
		/opt/Qt/6.9.0/macos/lib/QtWidgets.framework/Headers/qmessagebox.h \
		/opt/Qt/6.9.0/macos/lib/QtWidgets.framework/Headers/QInputDialog \
		/opt/Qt/6.9.0/macos/lib/QtWidgets.framework/Headers/qinputdialog.h \
		/opt/Qt/6.9.0/macos/lib/QtCore.framework/Headers/QFileInfo \
		/opt/Qt/6.9.0/macos/lib/QtCore.framework/Headers/qfileinfo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o configurationdialog.o configurationdialog.cpp

fielddefaultsmanager.o: fielddefaultsmanager.cpp fielddefaultsmanager.h \
		/opt/Qt/6.9.0/macos/lib/QtCore.framework/Headers/QString \
		/opt/Qt/6.9.0/macos/lib/QtCore.framework/Headers/qstring.h \
		/opt/Qt/6.9.0/macos/lib/QtCore.framework/Headers/QMap \
		/opt/Qt/6.9.0/macos/lib/QtCore.framework/Headers/qmap.h \
		/opt/Qt/6.9.0/macos/lib/QtCore.framework/Headers/QJsonObject \
		/opt/Qt/6.9.0/macos/lib/QtCore.framework/Headers/qjsonobject.h \
		/opt/Qt/6.9.0/macos/lib/QtCore.framework/Headers/QFile \
		/opt/Qt/6.9.0/macos/lib/QtCore.framework/Headers/qfile.h \
		/opt/Qt/6.9.0/macos/lib/QtCore.framework/Headers/QDir \
		/opt/Qt/6.9.0/macos/lib/QtCore.framework/Headers/qdir.h \
		/opt/Qt/6.9.0/macos/lib/QtCore.framework/Headers/QJsonDocument \
		/opt/Qt/6.9.0/macos/lib/QtCore.framework/Headers/qjsondocument.h \
		/opt/Qt/6.9.0/macos/lib/QtCore.framework/Headers/QStandardPaths \
		/opt/Qt/6.9.0/macos/lib/QtCore.framework/Headers/qstandardpaths.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o fielddefaultsmanager.o fielddefaultsmanager.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_buildexecutor.o: moc_buildexecutor.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_buildexecutor.o moc_buildexecutor.cpp

moc_configurationdialog.o: moc_configurationdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_configurationdialog.o moc_configurationdialog.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/LLVMBuilderGUI/bin || mkdir -p $(INSTALL_ROOT)/opt/LLVMBuilderGUI/bin
	$(DEL_FILE) -r $(INSTALL_ROOT)/opt/LLVMBuilderGUI/bin/LLVMBuilderGUI.app
	
	$(QINSTALL) LLVMBuilderGUI.app $(INSTALL_ROOT)/opt/LLVMBuilderGUI/bin/LLVMBuilderGUI.app
	-$(STRIP) $(INSTALL_ROOT)/opt/LLVMBuilderGUI/bin/LLVMBuilderGUI.app/Contents/MacOS/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/opt/LLVMBuilderGUI/bin/LLVMBuilderGUI.app
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/LLVMBuilderGUI/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

.SUFFIXES:

